### ISSUE TITLE
Fails to find accounts (IndexError: list index out of range)

### ISSUE THREAD

**Issue by YenForYang** [AmgdGocha/DriveFS-Sleuth#40]
The last time I tried to use this program I got the same error, but I messed around with `tasks.py` and/or `utils.py` to manually specify the list of possible account ids. This time, I thought I should bring it to your attention since it is troublesome to have to modify the script. I can't check what modifications I made exactly, I have to find the old clone of the repo I made first...but I believe just hardcoded a list of account ids in `experiments_id`. 

A quick fix would probably be to set the manual specification of `--accounts` to simply override the entire lookup process -- i.e. no `get_experiment_account_ids`, and just run with what was specified.

```
(drivefs_sleuth) (base) PS Z:\DriveFS-Sleuth> python .\drivefs_sleuth.py C:\Users\Richard\AppData\Local\Google\DriveFS --accounts=123456789123567891234 --html --csv --output z:\analysis_results
🚀 Starting DriveFS Sleuth...

🔄 Processing Path: C:\Users\Richard\AppData\Local\Google\DriveFS... [IN PROGRESS]
Traceback (most recent call last):
  File "Z:\DriveFS-Sleuth\drivefs_sleuth.py", line 11, in <module>
    execute()
  File "Z:\DriveFS-Sleuth\drivefs_sleuth\executor.py", line 197, in execute
    setup = Setup(drivefs_path, args.accounts)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\DriveFS-Sleuth\drivefs_sleuth\setup.py", line 352, in __init__
    for account_id, account_info in get_accounts(drivefs_path).items():
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\DriveFS-Sleuth\drivefs_sleuth\tasks.py", line 26, in get_accounts
    experiments_ids = get_experiment_account_ids(drivefs_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\DriveFS-Sleuth\drivefs_sleuth\utils.py", line 21, in get_experiment_account_ids
    return re.findall(r'\d+', cursor.fetchall()[0][0].decode('utf-8'))
```

The issue I believe is that `experiments.db` doesn't (necessarily) contain the `account_ids` it looks for.

**Comment by AmgdGocha** [comment]
This would be very interesting because for all the triages that I've ever worked on, the `experiments.db` always contains the account ids of all the accounts that ever logged on even if they've logged off. Did you simulate this scenarios by manually modifying the values in the  `experiments.db`?

Can you please mention the version of the google drive application you're trying to investigate? is it possible to share the `experiments.db`?

**Comment by AmgdGocha** [comment]
Closing this issue because it's been stale for a while. Feel free to reopen if you want.
