### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2034217: character maps to <undefined>

### ISSUE THREAD

**Issue by YenForYang** [AmgdGocha/DriveFS-Sleuth#42]
Error is as follows:

```
(drivefs_sleuth) (base) PS Z:\DriveFS-Sleuth> python .\drivefs_sleuth.py C:\Users\Richard\AppData\Local\Google\DriveFS --accounts=123456789123567891234 --html --csv --output z:\analysis_results
🚀 Starting DriveFS Sleuth...

🔄 Processing Path: C:\Users\Richard\AppData\Local\Google\DriveFS... [IN PROGRESS]
Traceback (most recent call last):
  File "Z:\DriveFS-Sleuth\drivefs_sleuth.py", line 11, in <module>
    execute()
  File "Z:\DriveFS-Sleuth\drivefs_sleuth\executor.py", line 197, in execute
    setup = Setup(drivefs_path, args.accounts)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\DriveFS-Sleuth\drivefs_sleuth\setup.py", line 352, in __init__
    for account_id, account_info in get_accounts(drivefs_path).items():
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\DriveFS-Sleuth\drivefs_sleuth\tasks.py", line 31, in get_accounts
    'email': lookup_account_id(drivefs_path, account_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Z:\DriveFS-Sleuth\drivefs_sleuth\utils.py", line 40, in lookup_account_id
    logs = logs_file.read()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Richard\scoop\apps\miniconda3\current\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2034217: character maps to <undefined>
```

I did a simply modification by changing the `open()` in `lookup_account_id` to open as utf8, which fixes the issue.

**Comment by AmgdGocha** [comment]
Resolved by: https://github.com/AmgdGocha/DriveFS-Sleuth/pull/41
